//
//  BooksListRouter.swift
//  BooksArchiveDemo
//
//  Created by kamalraj venkatesan on 14/08/19.
//  Copyright (c) 2019 kamalraj venkatesan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BooksListRoutingLogic {
    func navigateToDetailView(index: Int)
}

protocol BooksListDataPassing
{
    var dataStore: BooksListDataStore? { get }
}

class BooksListRouter: NSObject, BooksListRoutingLogic, BooksListDataPassing
{
    weak var viewController: BooksListViewController?
    var dataStore: BooksListDataStore?
    
    // MARK: Routing
    func navigateToDetailView(index: Int) {
        
        guard let book = dataStore?.books?[index] else {
            return
        }
        
        let vc = self.viewController?.storyboard?.instantiateViewController(withIdentifier: "BookDetailViewController") as! BookDetailViewController
        vc.book = book
        self.viewController?.navigationController?.pushViewController(vc, animated: true)
    }
}
