//
//  BooksListInteractor.swift
//  BooksArchiveDemo
//
//  Created by kamalraj venkatesan on 14/08/19.
//  Copyright (c) 2019 kamalraj venkatesan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BooksListBusinessLogic
{
  func doSomething(request: BooksList.Something.Request)
}

protocol BooksListDataStore
{
  //var name: String { get set }
}

class BooksListInteractor: BooksListBusinessLogic, BooksListDataStore
{
  var presenter: BooksListPresentationLogic?
  var worker: BooksListWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BooksList.Something.Request)
  {
    worker = BooksListWorker()
    worker?.doSomeWork()
    
    let response = BooksList.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
