//
//  BooksListPresenter.swift
//  BooksArchiveDemo
//
//  Created by kamalraj venkatesan on 14/08/19.
//  Copyright (c) 2019 kamalraj venkatesan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BooksListPresentationLogic
{
    func presentBooks(response: BooksList.getBooks.Response)
}

class BooksListPresenter: BooksListPresentationLogic
{
    weak var viewController: BooksListDisplayLogic?
    
    // MARK: Do something
    
    func presentBooks(response: BooksList.getBooks.Response)
    {
        let viewModel = BooksList.getBooks.ViewModel()
        viewController?.displayListOfBooks(viewModel: viewModel)
    }
}
