//
//  BookDetailInteractor.swift
//  BooksArchiveDemo
//
//  Created by kamalraj venkatesan on 14/08/19.
//  Copyright (c) 2019 kamalraj venkatesan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailBusinessLogic
{
    func doSomething(request: BookDetail.ShowBook.Request)
}

protocol BookDetailDataStore
{
    //var name: String { get set }
}

class BookDetailInteractor: BookDetailBusinessLogic, BookDetailDataStore
{
    var presenter: BookDetailPresentationLogic?
    var worker: BookDetailWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: BookDetail.ShowBook.Request)
    {
        let response = BookDetail.ShowBook.Response(book: request.book)
        presenter?.presentSomething(response: response)
    }
}
