//
//  BookDetailModels.swift
//  BooksArchiveDemo
//
//  Created by kamalraj venkatesan on 14/08/19.
//  Copyright (c) 2019 kamalraj venkatesan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BookDetail
{
    // MARK: Use cases
    
    enum ShowBook
    {
        struct Request
        {
            let book: Book?
        }
        struct Response
        {
            let book: Book?
        }
        struct ViewModel
        {
            let title: String?
            let imageUrl: String?
            let author: String?
            let genre: String?
        }
    }
}
