//
//  BookDetailPresenter.swift
//  BooksArchiveDemo
//
//  Created by kamalraj venkatesan on 14/08/19.
//  Copyright (c) 2019 kamalraj venkatesan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookDetailPresentationLogic
{
    func presentSomething(response: BookDetail.Something.Response)
}

class BookDetailPresenter: BookDetailPresentationLogic
{
    weak var viewController: BookDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: BookDetail.Something.Response)
    {
        let viewModel = BookDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
